### PR TITLE
Some small UI changes

### LINKED ISSUE #862: Make Normal emoji larger when in a message with text
### The Problem

Normal emoji are very small when next to text

### The Solution

make them larger (same as when custom emoji are in the same situation)

### Alternatives

_No response_

### Additional context

_No response_

### Happens in the latest version

- [X] Yes, this feature is still missing.

### LINKED ISSUE #866: System Theme Isn't Completely Respected by Dialogue Windows and Chatrooms
### Describe the bug

Nheko's dialogue windows don't respect the system's drop-down lists, switches, buttons, and scrollbars.
This is also the case for chatroom scrollbars as well.

-----

For reference:

- [**Link to the system color theme**](https://store.kde.org/p/1403409)
- The KDE / Qt "Application Style" theme: **Oxygen**

**System Info:**

**OS:** Arch Linux x86_64
**Host:** MS-7B93
**Kernel:** [Linux 5.14.21-230-tkg-pds-llvm](https://github.com/frogging-family/linux-tkg)
**DE:** Plasma 5.23.4
**WM:** KWin
**Board:** Micro-Star International Co., Ltd. MPG X570 GAMING PRO CARBON WIFI (MS-7B93)

### To Reproduce

1. Go to **User Settings**
2. Enable system theming
3. Observe the the applied theme, closely
4. Exit User Settings
5. Open a chatroom, if you haven't already
6. See that chatroom scrollbars don't respect the system theme
7. Open a matrix user's profile in the chatroom
8. See that buttons do not respect the system theme
9. Open the chatroom's settings
10. See that drop-downs, switches, and buttons do not respect the system's theme
11. Open the chatroom's member info
12. See that this window also doesn't respect the system theme for the mentioned UI elements

### What happened?

The UI didn't completely respect my system's Qt theming.

### Expected behavior

I expected the UI to completely respect my system's Qt theming.

### Screenshots

**Example:**
image

**What the UI should look more like:**
image

### Version

0.9.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

Clang 13.0.0-4

### Desktop Environment

KDE Plasma - Kwin Window Manager

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
https://gist.github.com/ThisNekoGuy/f144f8e1ff3618448475a336955e0edf

(The log is too large to paste here)
```

### Backtrace

_No response_

### LINKED ISSUE #1133: The warning to turn on E2EE in a room appears again if you press "cancel".
### Describe the bug

The warning to turn on E2EE in a room appears again if you press "cancel".

### To Reproduce

1. Go to 'room setting'
2. Activate 'encryption'
3. See warning
4. Press 'cancel'
5. Warning appears again

### What happened?

_No response_

### Expected behavior

_No response_

### Screenshots

_No response_

### Version

0.10.0

### Operating system

Linux

### Installation method

_No response_

### Qt version

5.15.5

### C++ compiler

gcc-11.3.0

### Desktop Environment

just an i3

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

_No response_

### Backtrace

_No response_

### LINKED ISSUE #1297: Long nicks and user IDs break GUI in room user list
### Describe the bug

Tite.

### To Reproduce

Open user list in room

### What happened?

hneko 0 10 2 - issue - 004

### Expected behavior

Not what happened.

### Screenshots

_No response_

### Version

0.10.2

### Operating system

Windows

### Installation method

_No response_

### Qt version

_No response_

### C++ compiler

_No response_

### Desktop Environment

_No response_

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

_No response_

### Backtrace

_No response_

### LINKED ISSUE #1378: Space summary page should have a way of leaving the space
### The Problem

There's no way to leave the space from the space room view, it took me a moment to realise I needed to right click on the room list.

### The Solution

Add a leave button to the summary screen, or alternatively in room settings.

### Alternatives

_No response_

### Additional context

_No response_

### Happens in the latest version

- [X] Yes, this feature is still missing.

### PR DESCRIPTION
**Pull request by LorenDB**
Fixes #862
Fixes #1297
Fixes #866
Fixes #1133 
Fixes #1378

### CODE REVIEW

**Comment by LorenDB** [comment]
Apart from the spinner commit, these are all trivial tweaks to bring things in line with general expectations for UI behavior.

The spinner commit is there because I noticed we had two spinners, and one was only used in one place, so I thought it would look nice to have the one used everywhere. If public sentiment runs opposite, I can drop it. ¯\\\_(ツ)_/¯

**Comment by LorenDB** [comment]
And I went ahead and added an emoji font upscale.

File: src/Utils.cpp [hunk 1]
```diff
@@ -141,7 +141,7 @@ utils::replaceEmoji(const QString &body)
         if (!insideTag && utils::codepointIsEmoji(code)) {
             if (!insideFontBlock) {
                 fmtBody += QStringLiteral("<font face=\"") % UserSettings::instance()->emojiFont() %
-                           QStringLiteral("\">");
+                           QStringLiteral("\" size=\"4\">");
```
Comment (deepbluev7) [inline src/Utils.cpp:144]: This should really be dependent on the large emoji setting instead of forced on everyone.

**Comment by deepbluev7** [comment]
Apart from the emoji size, most of these look fine codewise, thank you :)

File: src/Utils.cpp (hunk 1 above)
Comment (LorenDB) [reply src/Utils.cpp:144]: Hm, that is a good observation, but I think there are at least 2 reasons that that should not be dependent:

1. The emoji by default are nearly undecipherable in many cases where they are not upscaled (although ymmv if you have increased your overall font size).
2. This would require us to reprocess all displayed messages every time the large emoji setting was changed, which probably would be overkill.

Comment (LorenDB) [reply src/Utils.cpp:144]: Although if you think there is a good way to quickly reprocess fonts or if it is fine to not resize the emoji until a restart has happened, then I have a patch that I can add to this PR for that.

Comment (deepbluev7) [reply src/Utils.cpp:144]: Well, I don't want larger emoji than my text size. It just looks wrong to me. Imo just reusing the setting for the large emoji makes the most sense then, to not add too many toggles. I don't really care, if that requires a restart (or switching rooms) :)

Comment (LorenDB) [reply src/Utils.cpp:144]: Fair enough then. I have toyed with the idea of having an indicator for settings that require a restart, so I could maybe add that sometime to make this obvious.

File: src/Utils.cpp [hunk 2]
```diff
@@ -141,7 +141,11 @@ utils::replaceEmoji(const QString &body)
         if (!insideTag && utils::codepointIsEmoji(code)) {
             if (!insideFontBlock) {
                 fmtBody += QStringLiteral("<font face=\"") % UserSettings::instance()->emojiFont() %
-                           QStringLiteral("\">");
+                           QStringLiteral("\"") %
+                           (UserSettings::instance()->enlargeEmojiOnlyMessages()
+                              ? QStringLiteral(" size=\"4\"")
+                              : QString{}) %
+                           QStringLiteral(">");
```
Comment (deepbluev7) [inline src/Utils.cpp:148]:
```suggestion
                           (UserSettings::instance()->enlargeEmojiOnlyMessages()
                              ? QStringLiteral("\" size=\"4\">")
                              : QStringLiteral("\">"));
```

**Comment by deepbluev7** [comment]
Thank you :)
