### PR TITLE
Fix room leaving related bugs and few minor bugs

### LINKED ISSUE #460: The room list does not update immediately when a room is added to a hidden tag
### To Reproduce
1. Right click on a tag and hide all the rooms belonging to that tag.
2. Add a room to the hidden tag
3. Observe that the room is still shown in the room list.

### PR DESCRIPTION
**Pull request by Jedi18**
1) We don't check to see if the room was found in the removeRoom function, so we dereference the end iterator causing the crash. The removeRoom function is called twice so that's why this happens (once by clicking the remove room and another time when the ui is synced and we remove the left rooms)

2) A similar bug happens when we fetch the firstRoom, the firstRoom functions loops through elements in the contentsLayout (which still contains the removed room) and using the at function throws an exception. So added another check here.

3) Clicking invite button adds the user id text in the input field (if the input field is not empty)

4) Fixes #460 Room list does not update on adding room to hidden tag (and also does not update when you remove tag from a room). The communityChanged signal was not being emitted in the syncTags functions

### CODE REVIEW

File: src/dialogs/InviteUsers.cpp [hunk 1]
```diff
@@ -65,6 +65,10 @@ InviteUsers::InviteUsers(QWidget *parent)
 
         connect(inviteeInput_, &TextField::returnPressed, this, &InviteUsers::addUser);
         connect(confirmBtn_, &QPushButton::clicked, [this]() {
+                if (!inviteeInput_->text().isEmpty()) {
```
Comment (deepbluev7) [inline src/dialogs/InviteUsers.cpp:68]: Can you add an extra trim here? Otherwise it may become confusing, if you just have a space in the input.

**Review by deepbluev7 — COMMENTED** [review]
Looks great, thanks! Just have one small suggestion.

**Comment by deepbluev7** [comment]
Thanks a lot!
