### PR TITLE
Keep DBUS from blocking

### LINKED ISSUE #233: Borked DBUS can make nheko hang on startup
### Describe the bug

If you don't have a notification deamon running to accept notifications, Nheko can hang on startup

### Expected behavior

It should disable notifications or otherwise prevent the hang or work around it.

### PR DESCRIPTION
**Pull request by LorenDB**
Is it OK to "delete" a function like this? It just ended up being most logical to move everything into postNotification. Also, I added all the Q_UNUSED calls because my builds were somehow set to `-Werror=unused-variable` or something like that.

Closes #233

### CODE REVIEW

File: src/notifications/ManagerLinux.cpp [hunk 1]
```diff
@@ -79,15 +75,18 @@ NotificationsManager::showNotification(const QString summary,
...
+        QDBusPendingCallWatcher watcher{QDBusPendingReply{call}};
+        connect(&watcher,
+                &QDBusPendingCallWatcher::finished,
+                this,
+                [&watcher, this, &roomid, &eventid]() {
+                        if (watcher.reply().type() == QDBusMessage::ErrorMessage)
+                                qDebug() << "D-Bus Error:" << watcher.reply().errorMessage();
+                        else
+                                notificationIds[watcher.reply().arguments().first().toUInt()] =
+                                  roomEventId{roomid, eventid};
```
Comment (deepbluev7) [inline src/notifications/ManagerLinux.cpp:88]: Are you sure this code is ever executed? You are connecting to a local variable, so you probably get disconnected immediately again, since the variable gets destroyed. Instead you need to heap allocate it and remove it with deleteLater() in the slot, I think.

File: src/notifications/ManagerLinux.cpp [hunk 2]
```diff
@@ -44,29 +52,17 @@ NotificationsManager::postNotification(const QString &roomid,
...
-uint
-NotificationsManager::showNotification(const QString summary,
-                                       const QString text,
-                                       const QImage image)
-{
+        Q_UNUSED(icon)
+
         QVariantMap hints;
-        hints["image-data"] = image;
+        hints["image-data"] = sender + ": " + text;
```
Comment (deepbluev7) [inline src/notifications/ManagerLinux.cpp:58]: No? :D

File: src/notifications/ManagerLinux.cpp [hunk 3]
```diff
@@ -44,29 +52,17 @@ NotificationsManager::postNotification(const QString &roomid,
...
-        argumentList << "nheko"; // app_name
-        argumentList << (uint)0; // replace_id
-        argumentList << "";      // app_icon
-        argumentList << summary; // summary
-        argumentList << text;    // body
+        argumentList << "nheko";  // app_name
+        argumentList << (uint)0;  // replace_id
+        argumentList << "";       // app_icon
+        argumentList << roomname; // summary
+        argumentList << text;     // body
```
Comment (deepbluev7) [inline src/notifications/ManagerLinux.cpp:65]: This was sender + ": " + text before, right?

Comment (LorenDB) [reply src/notifications/ManagerLinux.cpp:65]: No, `roomname` was passed to `showNotification` as `summary`

File: src/notifications/ManagerLinux.cpp [hunk 4]
```diff
@@ -79,15 +75,17 @@ NotificationsManager::showNotification(const QString summary,
...
+        auto call    = notifyApp.asyncCallWithArgumentList("Notify", argumentList);
+        auto watcher = new QDBusPendingCallWatcher{QDBusPendingCall{QDBusPendingReply{call}}};
+        connect(
+          watcher, &QDBusPendingCallWatcher::finished, this, [watcher, this, &roomid, &eventid]() {
+                  if (watcher->reply().type() == QDBusMessage::ErrorMessage)
+                          qDebug() << "D-Bus Error:" << watcher->reply().errorMessage();
+                  else
+                          notificationIds[watcher->reply().arguments().first().toUInt()] =
+                            roomEventId{roomid, eventid};
+                  delete watcher;
```
Comment (deepbluev7) [inline src/notifications/ManagerLinux.cpp:87]: You need deleteLater, otherwise this crashes.

File: src/notifications/ManagerLinux.cpp (hunk 2 above)
Comment (LorenDB) [reply src/notifications/ManagerLinux.cpp:58]: Oops, I think I got that messed up.
