### PR TITLE
Fix emoji related issues

### LINKED ISSUE #433: Close emoji autocompleter if a space is typed after :
### Describe the bug

It's reasonably common to put a colon in a message, and while I understand the use of having the autocompleter match spaces in the name of an emoji, if a space is typed right after the colon the autocompleter should close because someone isn't looking for the emoji then, they are just typing a colon.

### To Reproduce
1. Type : in the input box
2. Type a space
3. Observer how the autocompleter doesn't close.

### Expected behavior

The autocompleter should close.

### LINKED ISSUE #438: Focus input field after selecting an emoji from the emoji picker
I either want to type some more or I want to hit enter to send the message, Neither options works when you weren't in the input field beforehand.

### LINKED ISSUE #441: After sending a reaction the input field should be focussed
I usually send reactions while chatting with other people. So I want to get right back to writing after adding a reaction.

### PR DESCRIPTION
**Pull request by Jedi18**
1) Add default option for emoji font family in settings
2) Fixes #441 input field is focussed after reacting to a message
3) Fixes #433 closes emoji autocompleter if space is pressed after colon
4) Fixes #438 focus input field after selection from emoji picker

### CODE REVIEW

File: src/UserSettingsPage.cpp [hunk 1]
```diff
@@ -725,6 +725,7 @@ UserSettingsPage::UserSettingsPage(QSharedPointer<UserSettings> settings, QWidge
         // TODO: Is there a way to limit to just emojis, rather than
         // all emoji fonts?
         auto emojiFamilies = fontDb.families(QFontDatabase::Symbol);
+        emojiFontSelectionCombo_->addItem(QString("default"));
```
Comment (deepbluev7) [inline src/UserSettingsPage.cpp:728]: Selecting this should be handled specially, so that the font is not actually set to default. It should also be translatable.

**Review by deepbluev7 — COMMENTED** [review]
Looks good to me apart from a small nitpick.

File: src/UserSettingsPage.cpp (hunk 1 above)
Comment (Jedi18) [reply src/UserSettingsPage.cpp:728]: The reason I set it to "default" is because here https://github.com/Nheko-Reborn/nheko/blob/4aefac08a4b57e6fb344cd8cffb0b6e32698e0ba/src/UserSettingsPage.cpp#L104  . So it works properly without needing to specially handle it.

But yeah translations, so can I rewrite that to 
`emojiFontSelectionCombo_->addItem(tr("default"));`

and then
`emojiFont_         = settings.value("user/emoji_font_family", tr("default")).toString();`

I guess that would work right?

Comment (deepbluev7) [reply src/UserSettingsPage.cpp:728]: Yeah, that should work. You may also want to do the same for normal fonts. I forgot we already handled default specifically.

File: src/UserSettingsPage.cpp [hunk 2]
```diff
@@ -93,15 +93,15 @@ UserSettings::load(std::optional<QString> profile)
         sortByImportance_     = settings.value("user/sort_by_unread", true).toBool();
         readReceipts_         = settings.value("user/read_receipts", true).toBool();
         theme_                = settings.value("user/theme", defaultTheme_).toString();
-        font_                 = settings.value("user/font_family", "default").toString();
+        font_                 = settings.value("user/font_family", tr("Default")).toString();
```
Comment (deepbluev7) [inline src/UserSettingsPage.cpp:96]: I think that will cause issues. You should translate that to default in the setFont functions and such instead, I think

**Comment by deepbluev7** [comment]
Seems to work well, just needs fixing for the localization stuff I commented on. The font selector also does not list default, but empty works there as well, so that is fine

**Comment by deepbluev7** [comment]
Yep, seems to work, thank you!
