### PR TITLE
QML all the things, part 2: Read receipts dialog

### LINKED ISSUE #397: Read receipts dialog is not touch-scrollable
### Describe the bug
The read receipts dialog cannot be scrolled by touch. This is likely due to the fact the this dialog is not written in QML.

### To Reproduce
1. Open a read receipts dialog for a message with a lot of read receipts (enough that the read receipts window doesn't display them all).
2. Try scrolling with a touch screen.

### Expected behavior
The dialog should scroll.

### System:

- Nheko version: 0.8.0-a6717007 (likely any version will suffice)
- Installation method: local build
- Operating System: Linux
- Qt version: 5.12.8
- C++ compiler: not sure, either clang or gcc
- Desktop Environment: Plasma 5.18.5

### PR DESCRIPTION
**Pull request by LorenDB**
- QML the read receipts list
- Don't access null property (fixes QML warning)

Fixes #397

### CODE REVIEW

File: src/ReadReceiptsModel.cpp [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+        }
+}
+
+void
+ReadReceiptsModel::addUsers(
+  const std::multimap<uint64_t, std::string, std::greater<uint64_t>> &users)
+{
+        auto oldLen = readReceipts_.length();
+
+        beginInsertRows(QModelIndex{}, oldLen, users.size() - 1);
```
Comment (deepbluev7) [inline src/ReadReceiptsModel.cpp:81]: This won't work. You need to pass exactly where you are inserting elements. Not just assume they will land at the end of the list and then sort it.

File: resources/qml/ReadReceipts.qml [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+
+    property ReadReceiptsModel readReceipts
+
+    x: MainWindow.x + (MainWindow.width / 2) - (width / 2)
+    y: MainWindow.y + (MainWindow.height / 2) - (height / 2)
+    height: 380
+    width: 340
+    minimumHeight: 380
+    minimumWidth: headerTitle.width + 2 * Nheko.paddingMedium
+    palette: Nheko.colors
```
Comment (deepbluev7) [inline resources/qml/ReadReceipts.qml:21]: This should probably still be of type Dialog, otherwise some WMs will reposition it wrong or not make it float.

File: src/ReadReceiptsModel.cpp (hunk 1 above)
Comment (LorenDB) [reply src/ReadReceiptsModel.cpp:81]: The existing count of elements is updated about 2 lines below that

Comment (deepbluev7) [reply src/ReadReceiptsModel.cpp:81]: This line says you are inserting the elements at the end. If you call sort, that is not necessarily true.

Comment (LorenDB) [reply src/ReadReceiptsModel.cpp:81]: If you have any suggestions for how to do this better, I would be glad to hear them though

Comment (LorenDB) [reply src/ReadReceiptsModel.cpp:81]: > This won't work. You need to pass exactly where you are inserting elements. Not just assume they will land at the end of the list and then sort it.

No, what I have does work. It first inserts more receipts. Then it calls `dataChanged` on the number of receipts that were previously there. (i.e. there are receipts a and b. We add c and d. The model adds 2 items, although the order is a, c, b, d for some reason. Now Qt sees the model as a, b, b, d. But the model updates the first 2 (existing) items, so Qt sees a,c, b, d.)

File: resources/qml/ReadReceipts.qml (hunk 2 above)
Comment (deepbluev7) [reply resources/qml/ReadReceipts.qml:21]: Why did you resolve this? The window type is still wrong, I'd say.

File: resources/qml/RoomMembers.qml [hunk 3]
```diff
@@ -9,7 +9,7 @@ import QtQuick.Layouts 1.12
 import QtQuick.Window 2.12
 import im.nheko 1.0
 
-ApplicationWindow {
+Dialog {
```
Comment (deepbluev7) [inline resources/qml/RoomMembers.qml:12]: Why did you change this?

File: src/ReadReceiptsModel.cpp (hunk 1 above)
Comment (deepbluev7) [reply src/ReadReceiptsModel.cpp:81]: Well, then just call resetModel instead of insert + dataChanged. But really, you should probably call insert at the right places?

Comment (deepbluev7) [reply src/ReadReceiptsModel.cpp:81]: If you don't want to write that logic yourself, put a sortproxy in front of the model.

File: resources/qml/RoomMembers.qml (hunk 3 above)
Comment (LorenDB) [reply resources/qml/RoomMembers.qml:12]: I thought that was what you meant. I must have misunderstood. What exactly did you want as far as making this a dialog?

Comment (deepbluev7) [reply resources/qml/RoomMembers.qml:12]: The other windows have type: Qt.Dialog or so. We did that because otherwise the windows didn't get positioned correctly. Although we can probably remove that, once everything is qml and we can set a parent window?

File: resources/qml/Root.qml [hunk 4]
```diff
@@ -164,6 +172,18 @@ Page {
...
+        function onOpenReadReceiptsDialog(rr) {
+            var dialog = readReceiptsDialog.createObject(timelineRoot, {
+                "readReceipts": rr,
+                "room": Rooms.currentRoom
+            });
+            dialog.show();
+        }
+
+        target: Rooms.currentRoom
+    }
```
Comment (deepbluev7) [inline resources/qml/Root.qml:185]: Can you move this into the TimelineView and attach to the room instead of the Rooms.currentRoom? Otherwise you can only open read receipts in one room once we allow people to open multiple windows each showing a different room (tear out rooms basically).

Comment (deepbluev7) [reply resources/qml/Root.qml:185]: Passing in the currentRoom here also is a bit racy that the rr and room don't match up.

Comment (LorenDB) [reply resources/qml/Root.qml:185]: Sure, I'll be glad to do that.

File: resources/qml/ReadReceipts.qml [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+        onActivated: readReceiptsRoot.close()
+    }
+
+    ColumnLayout {
+        anchors.fill: parent
+        anchors.margins: Nheko.paddingMedium
+        spacing: Nheko.paddingMedium
+
+        Label {
+            id: headerTitle
```
Comment (deepbluev7) [inline resources/qml/ReadReceipts.qml:37]: This is missing a readable color

File: src/ReadReceiptsModel.cpp [hunk 6]
```diff
@@ -0,0 +1,130 @@
...
+        auto days = then.daysTo(now);
+
+        if (days == 0)
+                return tr("Today %1")
+                  .arg(QLocale::system().toString(then.time(), QLocale::ShortFormat));
+        else if (days < 2)
+                return tr("Yesterday %1")
+                  .arg(QLocale::system().toString(then.time(), QLocale::ShortFormat));
+        else if (days < 7)
+                return QString("%1 %2")
```
Comment (deepbluev7) [inline src/ReadReceiptsModel.cpp:115]:
```suggestion
                return tr("Today, %1")
                  .arg(QLocale::system().toString(then.time(), QLocale::ShortFormat));
        else if (days < 2)
                return tr("Yesterday, %1")
                  .arg(QLocale::system().toString(then.time(), QLocale::ShortFormat));
        else if (days < 7)
                //: %1 is the name of the current day, %2 is the time the read receipt was read. The result may look like this: Monday, 7:15
                return QString("%1, %2")
```

File: resources/qml/ReadReceipts.qml (hunk 5 above)
Comment (LorenDB) [reply resources/qml/ReadReceipts.qml:37]: What would you make it? colors.text?

Comment (deepbluev7) [reply resources/qml/ReadReceipts.qml:37]: For example. Whatever the other dialogs use :3
