### PR TITLE
Get category switching working

### LINKED ISSUE #231: React Emoji Picker: Navigation buttons don't work
### Describe the bug
Can't use the navigation buttons on the bottom of the emoji picker

### To Reproduce
1. Click on the react button to any message
2. Click on one of the navigation buttons
3. Nothing happens

### Expected behavior
The emoji picker should scroll to the right category

### System:

- Nheko version 0.7.2
- Installation method: nix
- Operating System: nixos
- Qt version: 5.12.7
- C++ compiler: gcc 9.3.0
- Desktop Environment: sway

### Logs

`[2020-06-25 16:06:50.310] [qml] [warning] qrc:/qml/emoji/EmojiPicker.qml:234: Error: Cannot assign double to an unregistered type (qrc:/qml/emoji/EmojiPicker.qml:234, )`

### PR DESCRIPTION
**Pull request by LorenDB**
I apologize, but I could *not* get the added newline at the end of EmojiModel.h removed.

Fixed #231

### CODE REVIEW

File: src/emoji/Provider_new.cpp [hunk 1]
```diff
@@ -9,7693 +9,7693 @@
 using namespace emoji;
 const QVector<Emoji> emoji::Provider::emoji = {
   // People
-  Emoji{QString::fromUtf8("\xf0\x9f\x98\x80"), "grinning face", emoji::EmojiCategory::People},
+  Emoji{QString::fromUtf8("\xf0\x9f\x98\x80"), "grinning face", emoji::Emoji::Category::People},
```
Comment (deepbluev7) [inline src/emoji/Provider_new.cpp:12]: This is actually a generated file, so you need to update scripts/emoji_codegen.py as well!

**Comment by deepbluev7** [comment]
Fails linting

**Comment by LorenDB** [comment]
> Fails linting

Fixed
