### PR TITLE
Move away from using an event loop to access secrets

### LINKED ISSUE #531: Device identity keys upload may lead to duplicate key upload
Currently our Nheko may upload the device keys multiple times, if we failed to restore the cache. This often breaks e2ee and we really should not be doing that.

The problem is as follows:

1. If we fail to restore the db, we create new device keys: https://github.com/Nheko-Reborn/nheko/blob/b31e74d9f64ed24592cd2c28ba28dbeea100de7c/src/ChatPage.cpp#L535
2. We then do an initial sync, where we always upload identity keys: https://github.com/Nheko-Reborn/nheko/blob/b31e74d9f64ed24592cd2c28ba28dbeea100de7c/src/ChatPage.cpp#L703
3. Because every key upload of us includes our identity keys: https://github.com/Nheko-Reborn/mtxclient/blob/master/lib/crypto/client.cpp#L188

We should fix all 3 of those issues:

1. If we fail to restore the db, we should
  - Prompt the user to export the current encryption keys
  - Log them out
2. We should not go to the initial sync or not include the identity key upload in the initial sync
3. We should only upload the identity keys exactly once, after login/registration.

Before that db loss with Nheko will always be sketchy and potentially break e2ee, because clients will refuse to accept the new identity keys.

### LINKED ISSUE #760: Sessions disappear if secret storage is locked at startup
### Describe the bug

I use keepassxc as secret storage service. If I open nheko before I've unlocked the database, a prompt will show up to unlock the database. Once completed nheko seems to have forgotten all about my existing login, and takes the session keys with it.

### To Reproduce

1. Set keepassxc as secret storage service.
2. Lock keepassxc database.
3. Open nheko.

### What happened?

Sessions and keys are gone.

### Expected behavior

Sessions and keys are restored automatically, or at least can be retrieved after they've been lost to places unknown.

### Screenshots

_No response_

### Version

0.8.2-07fbd13a | Linux

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.2+kde+r237

### C++ compiler

gcc-11.1.0

### Desktop Environment

i3

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2021-10-11 13:33:47.653] [ui] [info] Restoring window size 1916x1041
[2021-10-11 13:33:47.683] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2021-10-11 13:33:47.705] [ui] [info] jdenticon plugin not found.
[2021-10-11 13:33:47.950] [ui] [info] starting nheko 0.8.2-07fbd13a
[2021-10-11 13:34:21.278] [net] [info] Autodiscovery: No .well-known.
[2021-10-11 13:34:25.753] [db] [info] initializing LMDB
[2021-10-11 13:34:25.754] [crypto] [info] creating new olm account
[2021-10-11 13:34:25.794] [crypto] [info] Online key backup disabled.
[2021-10-11 13:34:25.794] [crypto] [info] ed25519   : ...
[2021-10-11 13:34:25.794] [crypto] [info] curve25519: ...
[2021-10-11 13:34:25.794] [crypto] [info] generating one time keys
[2021-10-11 13:34:26.071] [net] [info] uploaded 50 signed_curve25519 one-time keys
[2021-10-11 13:34:26.071] [net] [info] trying initial sync
[2021-10-11 13:34:27.000] [net] [info] initial sync completed
[2021-10-11 13:34:27.001] [db] [info] mark room !FOOBAR as encrypted
[...repeated many times...]
[2021-10-11 13:34:27.011] [crypto] [info] Could not find inbound megolm session (...)
[...repeated many times...]
[2021-10-11 13:34:27.083] [db] [info] No keys found for @me
```

### Backtrace

_No response_

### PR DESCRIPTION
**Pull request by deepbluev7**
Fixes messages in room flickering and being stuck

fixes #760
fixes #531 
relates to #770
relates to #789

### CODE REVIEW

File: src/ChatPage.cpp [hunk 1]
```diff
@@ -316,6 +316,65 @@ ChatPage::bootstrap(QString userid, QString homeserver, QString token)
...
+                            QCoreApplication::quit();
+                        }
+                        loadStateFromCache();
+                        return;
+                    } else if (cacheVersion == cache::CacheVersion::Newer) {
+                        QMessageBox::critical(
+                          this,
+                          tr("Incompatible cache version"),
+                          tr("The cache on your disk is newer than this version of Nheko "
+                             "supports. Please update or clear your cache."));
```
Comment (redsky17) [inline src/ChatPage.cpp:351]: should probably change to 'Please update *nheko'

Comment (deepbluev7) [reply src/ChatPage.cpp:351]: Hey, that was there for a year or so already! But fine ;p
